#pragma once

#define DRIVE_SPEED_CONTROLLER_FL_CHANNEL 1
#define DRIVE_SPEED_CONTROLLER_FR_CHANNEL 3
#define DRIVE_SPEED_CONTROLLER_BL_CHANNEL 0
#define DRIVE_SPEED_CONTROLLER_BR_CHANNEL 2

#define TALON_MOTOR 0

#define PCM 0
#define DOUBLE_SOLENOID_REVERSE_CHANNEL 0
#define DOUBLE_SOLENOID_FORWARD_CHANNEL 1
#define SINGLE_SOLENOID 2

#define SCFL_INVERTED false
#define SCBL_INVERTED false
#define SCFR_INVERTED false
#define SCBR_INVERTED false
