#pragma once

#define DRIVE_SPEED_CONTROLLER_FL_CHANNEL 1
#define DRIVE_SPEED_CONTROLLER_FR_CHANNEL 3
#define DRIVE_SPEED_CONTROLLER_BL_CHANNEL 0
#define DRIVE_SPEED_CONTROLLER_BR_CHANNEL 2

#define SCFL_INVERTED false
#define SCBL_INVERTED false
#define SCFR_INVERTED false
#define SCBR_INVERTED false

#define ARM_MOTOR 0

#define PCM 0


#define SINGLE_SOLENOID_1 1
#define SINGLE_SOLENOID_2 2
#define SINGLE_SOLENOID_3 3
#define SINGLE_SOLENOID_4 4
#define SINGLE_SOLENOID_5 5
#define SINGLE_SOLENOID_6 6
#define DOUBLE_SOLENOID_REVERSE_CHANNEL 7
#define DOUBLE_SOLENOID_FORWARD_CHANNEL 8

#define TOP_LIMIT_SWITCH 0
#define BOTTOM_LIMIT_SWITCH 1
